In [18]:
import pandas as pd
df = pd.read_excel(open("Continual monitoring data both areas-small.xlsx",'rb'), sheet_name='Brighton Terminal')
df.head()

,Date and Time,Date (MM/DD/YYYY),Time (HH:MM:SS),Date (MM/DD/YYYY).1,Time (HH:MM:SS).1,Time (Fract. Sec),Site Name,Fault Code,Battery V,Cable Pwr V,Temp °C,Cond µS/cm,...,nLF Cond µS/cm,TDS mg/L,ODO % sat,ODO mg/L,Turbidity FNU,TSS mg/L,pH,pH mV,ORP mV,ORP raw mV,Press psi a,Depth m
0,2014-03-03 16:34:52,41701,0.690880,2014-03-03,16:34:52,0,Deployment Site,0,6.2,0,8.385,31859.2,...,47485.0,NaN,87.6,8.46,3.23,0,8.16,-66.1,297.4,292.3,9.178,6.306
1,2014-03-03 16:44:52,41701,0.697824,2014-03-03,16:44:52,0,Deployment Site,0,6.2,0,8.369,31867.7,...,47518.0,NaN,85.6,8.27,2.75,0,8.17,-66.9,281.8,276.8,9.156,6.291
2,2014-03-03 16:54:52,41701,0.704769,2014-03-03,16:54:52,0,Deployment Site,0,6.2,0,8.365,31795.3,...,47414.9,NaN,85.6,8.27,2.48,0,8.18,-67.1,270.9,265.9,9.160,6.294
3,2014-03-03 17:04:52,41701,0.711713,2014-03-03,17:04:52,0,Deployment Site,0,6.2,0,8.367,31863.1,...,47513.6,NaN,85.4,8.25,2.17,0,8.17,-67.1,262.8,257.7,9.166,6.297
4,2014-03-03 17:14:52,41701,0.718657,2014-03-03,17:14:52,0,Deployment Site,0,6.2,0,8.367,31942.5,...,47631.7,NaN,84.7,8.18,2.25,0,8.19,-68.1,257.8,252.7,9.147,6.284

In [19]:
df.describe()

,Date (MM/DD/YYYY),Time (HH:MM:SS),Time (Fract. Sec),Fault Code,Battery V,Cable Pwr V,Temp °C,Cond µS/cm,SpCond µS/cm,Sal psu,nLF Cond µS/cm,TDS mg/L,ODO % sat,ODO mg/L,Turbidity FNU,TSS mg/L,pH,pH mV,ORP mV,ORP raw mV,Press psi a,Depth m
count,10032.000000,10032.000000,10032.0,10032.0,10032.000000,10032.0,10032.000000,10032.000000,10032.000000,10032.000000,10032.000000,0.0,10032.000000,10032.000000,10032.000000,10032.0,10032.000000,10032.000000,10032.000000,10032.000000,10032.000000,10032.000000
mean,41736.023824,0.499744,0.0,0.0,5.388118,0.0,11.282280,36544.346222,49490.013028,32.233357,50339.394378,NaN,92.276106,8.263662,3.119314,0.0,8.392257,-79.895774,66.202213,61.113985,9.236038,6.338153
std,20.117290,0.289332,0.0,0.0,0.279457,0.0,1.887861,2260.381415,921.497485,0.739727,929.125468,NaN,8.482643,0.878414,10.877102,0.0,0.067535,4.129431,24.675389,24.675172,0.229288,0.156801
min,41701.000000,0.000000,0.0,0.0,5.000000,0.0,8.214000,31113.100000,45795.800000,29.400000,46592.300000,NaN,63.200000,5.590000,0.510000,0.0,8.100000,-90.600000,-57.300000,-62.400000,8.527000,5.856000
25%,41719.000000,0.246435,0.0,0.0,5.200000,0.0,9.689000,34942.450000,49107.875000,31.940000,49930.150000,NaN,86.400000,7.570000,1.560000,0.0,8.340000,-83.000000,50.175000,45.100000,9.125750,6.262000
50%,41736.000000,0.496435,0.0,0.0,5.300000,0.0,11.162500,36687.300000,49665.450000,32.360000,50537.050000,NaN,91.900000,8.300000,2.190000,0.0,8.400000,-80.700000,64.700000,59.650000,9.265000,6.358000
75%,41753.000000,0.753380,0.0,0.0,5.600000,0.0,12.847000,38589.175000,50177.000000,32.820000,51017.100000,NaN,98.000000,8.890000,3.240000,0.0,8.440000,-76.400000,79.500000,74.400000,9.392000,6.445000
max,41771.000000,0.996435,0.0,0.0,6.200000,0.0,14.938000,40034.000000,50954.800000,33.360000,51827.300000,NaN,120.700000,11.030000,919.600000,0.0,8.570000,-63.100000,297.400000,292.300000,9.714000,6.665000

In [20]:
# Standard Data Science Helpers
import numpy as np
import pandas as pd
import scipy

import chart_studio.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

# Extra options
pd.options.display.max_rows = 30
pd.options.display.max_columns = 25

# Show all code cells outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [21]:


import os
from IPython.display import Image, display, HTML

In [23]:
import ipywidgets as widgets
from ipywidgets import interact, interact_manual

In [24]:
@interact
def show_articles_more_than(column='Battery V', x=4):
    display(HTML(f'<h2>Showing articles with more than {x} {column}<h2>'))
    display(df.loc[df[column] > x, ['Date and Time','Date (MM/DD/YYYY)','Time (HH:MM:SS)','Date (MM/DD/YYYY)','Time (HH:MM:SS)','Battery V','Temp °C','Cond µS/cm','SpCond µS/cm','Sal psu','nLF Cond µS/cm','ODO % sat','ODO mg/L','Turbidity FNU','TSS mg/L','pH','pH mV','ORP mV','ORP raw mV','Press psi a','Depth m']])

interactive(children=(Text(value='Battery V', description='column'), IntSlider(value=4, description='x', max=1…

In [30]:
@interact
def correlations(column1=list(df.select_dtypes('number').columns), 
                 column2=list(df.select_dtypes('number').columns)):
    print(f"Correlation: {df[column1].corr(df[column2])}")

interactive(children=(Dropdown(description='column1', options=('Date (MM/DD/YYYY)', 'Time (HH:MM:SS)', 'Time (…

In [38]:

@interact
def line_plot(x=list(df.select_dtypes('number').columns), 
                 y=list(df.select_dtypes('number').columns)[1:]):
    df.iplot(kind='line', x=x, y=y, mode='lines', 
             xTitle=x.title(), yTitle=y.title(), title=f'{y.title()} vs {x.title()}')

ValueError: Could not find plotting backend 'plotly'. Ensure that you've installed the package providing the 'plotly' entrypoint, or that the package has a top-level `.plot` method.

In [37]:
import cufflinks as cf

@interact
def scatter_plot(x=list(df.select_dtypes('number').columns), 
                 y=list(df.select_dtypes('number').columns)[1:],
                 theme=list(cf.themes.THEMES.keys()), 
                 colorscale=list(cf.colors._scales_names.keys())):
    
    df.iplot(kind='scatter', x=x, y=y, mode='markers', 
             xTitle=x.title(), yTitle=y.title(), 
             title=f'{y.title()} vs {x.title()}',
            theme=theme, colorscale=colorscale,
            dimensions=(1000, 750))

interactive(children=(Dropdown(description='x', options=('Date (MM/DD/YYYY)', 'Time (HH:MM:SS)', 'Time (Fract.…